spring:
  profiles:
    active:
      - test


---
spring:
  config:
    activate:
      on-profile:
        - dev
  info: "welcome to dev environment. we will work on dev environment"
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/hungerboxdev
    password: password
  application:
    name: hungerbox
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile:
        - test
  info: "welcome to test environment. we will work on test environment----new configuration"
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/hungerboxtest
    password: password
  application:
    name: hungerbox
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8082

---
spring:
  config:
    activate:
      on-profile:
        - prod
  info: "welcome to prod environment. we will work on prod environment"
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/hungerboxprod
    password: password
  application:
    name: hungerbox
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8083